---
title: "descriptives"
format: html
editor: visual
---

```{r}
library(tidyverse)

```

```{r}
files <- c("df_all.csv")

for (file in files) {
  cat("\n\n----", file, "----\n")
  df <- read_csv(file)
  
  cat("Unique students:", n_distinct(df$id), "\n")
  
  enrollment <- df %>%
    group_by(id) %>%
    summarise(years_enrolled = n_distinct(program_year)) %>%
    mutate(enrollment_type = if_else(years_enrolled > 1, "2+ years", "1 year")) %>%
    count(enrollment_type)
  
  print(enrollment)
  
  grade_summary <- df %>% 
     group_by(id) %>%
    count(grade, name = "n_students") %>% arrange(grade)
  print(grade_summary)
  
  missingness <- df %>%
    summarise(across(everything(), ~ mean(is.na(.)) * 100)) %>%
    pivot_longer(cols = everything(),
                 names_to = "variable",
                 values_to = "percent_missing")
  print(missingness)
}

```

```{r}
#just putting this here because I was running it to look at the other files and thought it might be helpful:

df_all %>% 
  group_by(program_year)%>%
  summarise(n_unique_ids = n_distinct(id))


table(df_all$program_year)
```

```{r}
df_student_year <- df_all %>%
  select(id, cal_year, program_year, grade) %>%
  distinct()


table_year_program <- df_student_year %>%
  group_by(cal_year, program_year) %>%
  summarise(
    n_students = n_distinct(id),
    .groups = "drop"
  ) %>%
  arrange(cal_year, program_year)

table_year_program

table_grade_distribution <- df_student_year %>%
  group_by(cal_year, program_year, grade) %>%
  summarise(
    n_students = n_distinct(id),
    .groups = "drop"
  ) %>%
  arrange(cal_year, program_year, grade)

table_grade_distribution

table_year_grade <- table_grade_distribution %>%
  group_by(cal_year, grade) %>%
  summarise(
    n_students = sum(n_students),
    .groups = "drop"
  )
table_year_grade_wide <- table_year_grade %>%
  pivot_wider(
    names_from = grade,
    values_from = n_students,
    values_fill = 0
  ) %>%
  arrange(cal_year)

table_year_grade_wide

table_grade_wide <- table_grade_distribution %>%
  pivot_wider(
    names_from = grade,
    values_from = n_students,
    values_fill = 0
  )

table_grade_wide

df_all %>%
  summarise(n_unique_students = n_distinct(id))
```

\
